### ISSUE TITLE
doesn't work - help to troubleshoot

### ISSUE THREAD

**Issue by samalikp** [jasonsbeer/ZoRAM-Amiga-2000-RAM#1] opened 2021-05-30 19:43 UTC
Hi, I've built the ZoRAM, but it doesn't work ... check other zorro memory card, it was correctly detected ... not sure due to the design or my soldering skills or faulty ram chip ... I've ordered new RAM chips from Aliexpress, but they have been used .... I've verified the correct programming of the Xilinx chip ... any help on how to troubleshoot?

**Comment by jasonsbeer** [comment] 2021-06-03 01:10
Greetings - Did you build the 0.5 revision board? I have not been tested it, but there is a trace missing between pin 1 of U4 and pin 1 of U3. Try running a bodge wire between those pins. As always, be sure to double check voltages and solder bridges. I uploaded Rev 0.7 that fixes that and adds ground planes. However, that is not tested either.

On a side note, I will probably not pursue this project any further as the creator of the project I based this on has released his own Zorro 2 RAM card. It shows as tested and working. It is the same basic components, although different RAM chips. I recommend you take a look over there if you are unable to get this one working.

[https://github.com/LIV2/GottaGoFastRAM2000](url)

**Comment by samalikp** [comment] 2021-06-03 08:44
Greetings,
thank you for the reply. Yes, I build version 0.5 ... when I ordered the
PCB, you release version 0.6 :-) ... I will run the bodge wire and let you
know the result.
I saw LIV2 version, nevertheless, I like yours a bit more, since it uses
only 1 memory chip instead of 4. Therefore, I hope you will not end this
project and you will continue.
Thx a lot.
Kind regards
Peter

**Comment by samalikp** [comment] 2021-06-04 07:07
Greetings,
I've done the bodge wire, but it doesn't work .... not sure how I should
proceed with troubleshooting ...
The CPLD programming is ok, it finishes with successful verification.
I've checked all connections based on the scheme ... All is ok. No
shortages.
I have oscilloscope, but do not know how to check the functionality of each
chip.
I have a logic probe as well ... but never used it before :-)
Any advice?

Kind regards
Peter

**Comment by jasonsbeer** [comment] 2021-06-05 21:46
I reviewed the original schematics and I have some information for you...

1) Do you have other zorro cards plugged in? Try removing them and see if that helps. Then see #2

2) There should be a 10k pull down resistor on _CFGIN. See if you can bodge a 10k resistor between pin 12 on the zorro slot (meaning the trace coming from pin 12) and ground. Missing this resistor means the auto config signal will not be oscillating correctly may not auto config.

3) I have upload new binaries for the Xilinx. In my original, I made changes to Matthew's code and may have broken it. I have included the correct UCF and Matthew's original verilog. If the above does not fix the issue, please build these files and try them. [https://github.com/jasonsbeer/ZoRAM-Amiga-2000-RAM/tree/main/Binaries](url)

4) The original gottagofastram included a 74LVC2G17 buffer between CLK and _CFGIN. The information on the github page suggests this buffer is not necessary, and indeed, it is not included in this project. Perhaps it is required for reliable function.

**Comment by samalikp** [comment] 2021-06-07 06:27
Good morning,

thx a lot for the reply. I will follow your suggestions and report back to
you.
Kind regards
Peter

**Comment by samalikp** [comment] 2021-06-13 11:13
Hi,
1. I removed all other zorro cards and try the board without 10k resistor
... the board is not working
2. added 10k resistor to _CFGIN ...  the board is not working
3. compiled the Verilog file, created jed file and program to the CPLD ...
the board is not working

Could you please make more comments into verilog files, so I would
understand more what is doing which part of the code?
Any other suggestions?

Kind regards
Peter

**Comment by Retrofletch** [comment] 2021-06-24 00:33
Hello!
I also have a couple of these boards that i was unable to bring up to life, except mine was rev0.7, tried different firmwares old and new.

Would be sad if project is dead and i have to toss the boards, its nice that LIV made an alternative, but soldering one easy chip instead of 4 annoying SOJ chips would be alot better :)

Just wanted to add, you mentioned a 10K pulldown resistor on _CFGIN and GND, however LIV's design does not have this, he only have one resistor and that is only for when you want to force 4mb.

**Comment by jasonsbeer** [comment] 2021-06-24 20:58
@samalikp 
@Retrofletch 
My comment on the 10k pull down is from the original gottagofastram. You can see it in the attached schematic clip. It can be tied low or high, but is tied low by default.

Unfortunately, I am not sure how much further I can go with this. My desire, and belief, was that it would be possible to modify the gottagofastram project to work directly in a zorro 2 slot. This may be a bad assumption, especially in light that LIV2 made a completely different design rather than adapting his existing project to zorro 2. I did not write the verilog and would have to do a lot of homework to completely understand it.

Tagging @liv2. I'm hoping he can shed some light on whether this concept can be made to work.

![cnfin-pulldown](https://user-images.githubusercontent.com/78610265/123330240-628da400-d503-11eb-8221-78f53687a343.png)

**Comment by LIV2** [comment] 2021-06-25 10:02
Hi,

The pull down is only needed on the original GGF because it needs to not be left floating, in a Zorro slot this signal is always driven by the motherboard so no pull down is required
The LVC2G17 on the original is there to clean up noise mainly from the clock but in the 2000 version I derive the clock from C1/C3 to get a clean clock. Either method will work fine in the 2000 though.

I think I should be able to help get this working but I don't have the time today - I'll take a look at everything tomorrow morning and let you know what I find

**Comment by Retrofletch** [comment] 2021-06-26 02:15
> I think I should be able to help get this working but I don't have the time today - I'll take a look at everything tomorrow morning and let you know what I find

Nice! If you think of a software or bodge related fix im available to test, can dm me here or pistorm discord :)

**Comment by LIV2** [comment] 2021-06-26 14:16
@jasonsbeer @Retrofletch 

On the A2000 there is a signal on the zorro slot called "Slave" which must be asserted so that buster will enable the zorro buffers which will allow the CPU to communicate with Zorro cards, This is why the board doesn't work and isn't detected

I've modified the source to provide this signal and other misc changes to make it work in a zorro slot however as there's no free pins on the CPLD we need to reuse one - in this case the READ pin to the CPLD can be used as I've added a hack to the code to detect reads/writes freeing up this pin.

[Here is the code/jed file](https://github.com/LIV2/ZoRAM-Amiga-2000-RAM/tree/main/Binaries)
To mod the board you will need to cut the trace where indicated here, then expose the copper by scraping off the solder mask and solder a wire from the trace to the SLAVE pin of the zorro connector
<img width="988" alt="mod" src="https://user-images.githubusercontent.com/955874/123515896-ad412480-d699-11eb-9a65-aab450a30d35.png">

**Comment by LIV2** [comment] 2021-06-26 20:53
Thanks to @Retrofletch for helping to test this, on his system the board is now detected by diagrom but causes a black screen & flashing power LED when booting kickstart. At least it's being detected now!

I will have to tweak timings a bit I think, probably for the R/W hack I had to do. I will try to continue on this tomorrow at some point

**Comment by samalikp** [comment] 2021-06-26 21:15
> Thanks to @Retrofletch for helping to test this, on his system the board is now detected by diagrom but causes a black screen & flashing power LED when booting kickstart. At least it's being detected now!
> 
> I will have to tweak timings a bit I think, probably for the R/W hack I had to do. I will try to continue on this tomorrow at some point

Excellent, I will test it on PCB version 0.5 tomorrow. Thanks a lot.

**Comment by Retrofletch** [comment] 2021-06-26 21:18
> > Thanks to @Retrofletch for helping to test this, on his system the board is now detected by diagrom but causes a black screen & flashing power LED when booting kickstart. At least it's being detected now!
> > I will have to tweak timings a bit I think, probably for the R/W hack I had to do. I will try to continue on this tomorrow at some point
> 
> Excellent, I will test it on PCB version 0.5 tomorrow. Thanks a lot.

the code posted above did not work it had some error, its a different code we got working somewhat.
In diagrom i was able to config it and do full memory test with the last changes he did.
So wait for working code, the one above did not work :)
But it is promising, it seems its only the autoconfig part that dosnt work correctly from what i can tell..

**Comment by samalikp** [comment] 2021-06-27 08:36
Hi guys,
great work. Thx for the info. I will do at least the cut and connect SLAVE
pin ... test the new code ... since I have 0.5 version it could be also
some other PCB issues ...

Kind regards
P.

**Comment by jasonsbeer** [comment] 2021-06-27 14:05
> Hi guys, great work. Thx for the info. I will do at least the cut and connect SLAVE pin ... test the new code ... since I have 0.5 version it could be also some other PCB issues ... Kind regards P.

@samalikp 
Only issue should be the need to bodge together pin 1 on U3 and U4. You can drop the 10k bodge.

@LIV2 
Thanks a bunch for helping with this. I owe you again.

**Comment by samalikp** [comment] 2021-06-27 18:12
I've done cut and connect SLAVE pin on PCB v 0.5 compiled the code and programmed the cpld ... Result black screen ...

**Comment by LIV2** [comment] 2021-06-27 20:53
Sent a file to @Retrofletch earlier today which resulted in things getting further but ultimately still ending up in a crash. I'm not sure why and without having a board in hand it's hard for me to tell for sure so I'll have to keep poking things and get people to test...

Anyway I've made some changes now, could someone please try [this jed file](https://raw.githubusercontent.com/LIV2/ZoRAM-Amiga-2000-RAM/main/Binaries/zoram-2.jed) and see what happens?

**Comment by Retrofletch** [comment] 2021-06-27 20:55
> Sent a file to @Retrofletch earlier today which resulted in things getting further but ultimately still ending up in a crash. I'm not sure why and without having a board in hand it's hard for me to tell for sure so I'll have to keep poking things and get people to test...
> 
> Anyway I've made some changes now, could someone please try [this jed file](https://raw.githubusercontent.com/LIV2/ZoRAM-Amiga-2000-RAM/main/Binaries/zoram-2.jed) and see what happens?

ill send you a board tomorrow if i get the time :)

**Comment by LIV2** [comment] 2021-06-30 16:03
I've received some boards from @Retrofletch now and will find some time this week to back further until I get it working :)

**Comment by samalikp** [comment] 2021-07-14 13:10
> I've received some boards from @Retrofletch now and will find some time this week to back further until I get it working :)

Hi LIV2,
any luck with the board?

**Comment by LIV2** [comment] 2021-07-14 13:39
I haven't been able to make it work yet but haven't been able to dedicate a lot of time to this so far, I have noticed that even when it passes memtests in DiagROM it still won't work with Kickstart so I wonder if there's an issue with back-to-back memory accesses or refresh for some reason.

The same code works on my own Z2 board design but it's a bit different - different CPLD, RAM and buffers but I cannot see any reason why this should not work though.

I'll figure it out :)

**Comment by Retrofletch** [comment] 2021-07-14 13:45
> I haven't been able to make it work yet but haven't been able to dedicate a lot of time to this so far, I have noticed that even when it passes memtests in DiagROM it still won't work with Kickstart so I wonder if there's an issue with back-to-back memory accesses or refresh for some reason.
> 
> The same code works on my own Z2 board design but it's a bit different - different CPLD, RAM and buffers but I cannot see any reason why this should not work though.
> 
> I'll figure it out :)

I did have it working in with some kickstarts on some of the test firmwares you sent me on my machines, i think 1.3 and 2.04 but then the latest one i tested broke that. what i mean by that is it showed up in workbench and seemed to test well, never got it working stable on 3.1 with any of the firmwares tho so it clearly wasnt completely stable.

**Comment by LIV2** [comment] 2021-07-18 14:14
I've finally managed to make mine work!

The instability is caused by the decoupling capacitors not being close enough to each ic's VCC pin - I have bodged on some 0603's to my board to resolve this issue and am now able to use the board without issues - memtests pass, I can play whdload games and it works fine even with my A2091 installed.

It's a bit tricky to do but possible with 0603 size caps. here's a photo of my board (ignore the bodge wire to the right of U4):
![IMG_4586](https://user-images.githubusercontent.com/955874/126070500-f1714f98-7a6a-41eb-8e5c-2101ebe8d6e5.jpg)
I also bodged two 1206 capacitors to the fat power traces on the bottom of the PCB, under the CPLD

It may also require the jed file [here](https://github.com/LIV2/ZoRAM-Amiga-2000-RAM/blob/caps/Binaries/zoram-2.jed)

I am now opening a Pull-request which updates the PCB layout to correct this

**Comment by jasonsbeer** [comment] 2021-07-19 01:27
Thanks again for your help Matthew! I truly believe you are the Amiga RAM Master. I have merged in your changes. This is certainly a learning opportunity for me...especially around cap placement. It does seem I did not put much thought into placing them. I will leave this open for a few days to see if there are additional comments.

**Comment by LIV2** [comment] 2021-07-19 07:33
> Thanks again for your help Matt! I truly believe you are the Amiga RAM Master.
Lol I wouldn't got that far :P

> I have merged in your changes. This is certainly a learning opportunity for me...especially around cap placement. It does seem I did not put much thought into placing them. I will leave this open for a few days to see if there are additional comments.

Same here, I have heard the advice to put them close but never seen what happens when they're not close enough - If I had the wisdom to think about that I probably would've figured it out a lot sooner! 

btw is there a good way to keep in contact regarding the A2000 board? I.e Discord/Twitter/Forums etc?

**Comment by jasonsbeer** [comment] 2021-07-20 00:42
> btw is there a good way to keep in contact regarding the A2000 board? I.e Discord/Twitter/Forums etc?

I check the english amiga board often and pop into the Amiga group on MeWe once in a while. I do not really frequent any other forums. I'm open to checking out discord for any Amiga or Commodore groups. Good news is that with a couple bodges, EATX Rev 1.1 is running great. It is almost certain I will label Rev 1.2 as the production candidate.

**Comment by LIV2** [comment] 2021-07-22 13:42
Small update, I should note that it may not work with some accelerators.
This is because the R/W detection hack relies on the behaviour of a regular 68000 that asserts UDS/LDS at the same time as AS for reads, but later for writes - but accelerators don't always do this.

Anyone else given the bodge a try? @Retrofletch  @samalikp ?

**Comment by Retrofletch** [comment] 2021-08-09 07:21
Just put in an order for a few boards with only a few small changes, so if they work jasons updated design that its based on should work aswell, will let you know when they get here in a week or so. 
Great work on the updated design jason 👍

**Comment by LIV2** [comment] 2021-08-09 14:54
I ordered v0.8 PCBs last week and got around to assembling one this morning and can report that it works for me :)

**Closed** 2021-10-10 16:58 UTC
